# Generated by Django 6.0.7 on 2026-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hotelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='hotelbooking',
            name='hotel_type',
            field=models.CharField(max_length=100),
        ),
    ]
