# Generated by Django 6.0.7 on 2026-07-18 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_hotelbooking_created_at_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelbooking',
            name='created_at',
        ),
    ]
